# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/semc/es209ra/extract-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \
    vendor/semc/es209ra/proprietary/libcamera.so:obj/lib/libcamera.so

# All the blobs necessary for passion
PRODUCT_COPY_FILES += \
    vendor/semc/es209ra/proprietary/akmd2:system/bin/akmd2 \
    vendor/semc/es209ra/proprietary/camfirm.bin:system/etc/firmware/camfirm.bin \
    vendor/semc/es209ra/proprietary/camfirm.bin:system/etc/firmware/camfirmware_updating1_icn.rle \
    vendor/semc/es209ra/proprietary/camfirm.bin:system/etc/firmware/camfirmware_updating2_icn.rle \
    vendor/semc/es209ra/proprietary/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/semc/es209ra/proprietary/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
    vendor/semc/es209ra/proprietary/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/semc/es209ra/proprietary/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/semc/es209ra/proprietary/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/semc/es209ra/proprietary/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/semc/es209ra/proprietary/libcamera.so:system/lib/libcamera.so \
    vendor/semc/es209ra/proprietary/libgsl.so:system/lib/libgsl.so \
    vendor/semc/es209ra/proprietary/libmm-omxcore.so:system/lib/libmm-omxcore.so \
    vendor/semc/es209ra/proprietary/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/semc/es209ra/proprietary/libOmxCore.so:system/lib/libOmxCore.so \
    vendor/semc/es209ra/proprietary/libOmxVdec.so:system/lib/libOmxVdec.so \
    vendor/semc/es209ra/proprietary/libOmxVidEnc.so:system/lib/libOmxVidEnc.so
